USE DapperTest;

CREATE TABLE Model1 (
      Id INT NOT NULL IDENTITY (1,1),
      Prop1 VARCHAR(45) NOT NULL,
      Prop2 VARCHAR(45) DEFAULT 'DEFAULT VALUE',
      Prop3 VARCHAR(45) NULL,
      PRIMARY KEY (Id)
);

CREATE TABLE Model2 (
      Model2Id INT NOT NULL IDENTITY,
      Prop1 VARCHAR(45) NOT NULL,
      PRIMARY KEY (Model2Id)
);

CREATE TABLE Model3 (
      Id1 UNIQUEIDENTIFIER NOT NULL,
      Id2 UNIQUEIDENTIFIER NOT NULL,
      Prop1 VARCHAR(45) NOT NULL,
      PRIMARY KEY (Id1, Id2)
);

CREATE TABLE Model4 (
      Id INT NOT NULL IDENTITY (1,1),
      Prop1 VARCHAR(45) NOT NULL,
      Prop2 VARCHAR(45) DEFAULT 'DEFAULT VALUE',
      Prop3 VARCHAR(45) NULL,
      PRIMARY KEY (Id)
);